In [1]:
my_list = [1, 2, 3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [10]:
np.random.rand(5)

array([0.85222345, 0.68875875, 0.59166154, 0.5604729 , 0.46883572])

In [11]:
np.random.rand(5, 5)

array([[0.14626432, 0.53971011, 0.1499179 , 0.7592246 , 0.3154344 ],
       [0.37437693, 0.14523412, 0.00894539, 0.63935849, 0.59706291],
       [0.09906129, 0.74692547, 0.47758692, 0.8828476 , 0.85431383],
       [0.50800755, 0.97422164, 0.80171154, 0.7254216 , 0.65255903],
       [0.32949034, 0.95622471, 0.2242214 , 0.84510399, 0.32285511]])

In [12]:
np.random.randn(4, 4)

array([[-1.70836419, -1.92667131,  0.06994645, -0.54054853],
       [ 0.46315332, -0.67879875, -0.81134668, -0.35778233],
       [-1.78550717, -1.59086713, -0.44081229, -0.10955326],
       [ 0.58772102, -2.07281096,  0.6780872 , -0.2122229 ]])

In [16]:
np.random.randint(1, 100, (3, 9))

array([[40, 76, 50, 97, 43, 78,  9, 34, 49],
       [24, 21, 48, 23, 20,  3, 62, 43, 85],
       [ 5, 29, 57, 91, 44, 99, 31,  1,  7]])

In [17]:
arr = np.arange(25)

In [18]:
ran_arr = np.random.randint(0, 50, 10)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
ran_arr

array([36,  6, 42, 45,  0, 14, 38, 32, 47, 20])

In [21]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
ran_arr.max()

47

In [23]:
ran_arr.argmax()

8

In [24]:
ran_arr.argmin()

4

In [25]:
ran_arr.dtype

dtype('int32')